name: Deploy front staging
on:
  push
jobs:
  Deploy-Front-Staging:
    runs-on: self-hosted
    steps:
      - name: SSH remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PRE_STAGING_SERVER_IP }}
          port: ${{ secrets.PRE_STAGING_SERVER_PORT }}
          username: ${{ secrets.PRE_STAGING_SERVER_USER }}
          key: ${{ secrets.PRE_STAGING_SERVER_ID_RSA }}
          script: |
            echo hello
            cd python
            echo hi
      - run: while  ! curl -sI ${{ vars.STAGING_FRONT_BASE_URL }} | grep 200; do sleep 1; done && echo "server is running"
