name: Deploy front staging
on:
  push
jobs:
  Deploy-Front-Staging:
    runs-on: ubuntu-latest
    steps:
      - name: SSH remote commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PRE_STAGING_SERVER_IP }}
          port: ${{ secrets.PRE_STAGING_SERVER_PORT }}
          username: ${{ secrets.PRE_STAGING_SERVER_USER }}
          key: ${{ secrets.PRE_STAGING_SERVER_ID_RSA }}
          script_stop: true
          script: |
            echo hello
            cd python
            echo hi
